export const listedUser = {
  signin: "/signin",
  signup: "/signup",
  forget: "/forget",
  reset: "/reset",
  sent: "/sent",
  verify: "/verify",
  registerMember: "/register",
  payment: "/payment",
  paid: "/paid",
  error: "/*",
  dashboard: "/dashboard",
  add: "add",
  detail: "detail",
  land: "land",
  planting: "planting",
  supplier: "supplier",
  finance: "finance",
  profile: "profile",
  test: "/test",
  dahsboardVerfi: "/dashboard/verif",
 
};

export const listedAdmin = {
  dashboard: "/admin/dashboard",
  finance: "/admin/finance",
  adminPendapatan: "/admin/pendapatan",
  adminAnggota: "/admin/anggota",
  detailAnggota: "/admin/anggota/detail",
  anggotaBaru: "/admin/anggota-baru",
  DetailAnggotaBaru: "/admin/detail-anggota-baru",
  lahan: "/admin/lahan",
  lahanBaru: "/admin/lahan-baru",
  pendapatan: "/admin/pendapatan",
  budidaya: "/admin/budidaya",
  simpanan: "/admin/simpanan",
  tagihan: "/admin/tagihan",
};
